// LIST ALL GAMES
const listKiss = () => {
    return [
        'WITCH', 'TOPGUN', 'FOOTBALL', 'EASTER', 'DASHENGNAOHAI', 'LIKUIPIYU', 'SUNWUKONG', 'JIN QIAN WA', 'FORTUNE PANDA', 'ROBIN HOOD', 'ALICE', 'SEASONS', 'PAN JIN LIAN',
        'MAGICAL SPIN', 'PIRATE SHIP ', 'HALLOWEEN PARTY', 'COOKIE POP', 'SHINING STARS', 'STONE AGE', 'WESTERN RANCH STORY', 'MONEY FEVER', 'TREASURE ISLAND', 'GOLDEN TREE',
        'SEA WORLD', 'RANCH STORY', 'CIRCUS', 'FIVE DRAGON', 'WEALTH', 'AZTEC', 'CRYSTAL', 'GARDEN', 'GREEN LIGHT', 'VICTORY', 'DRAGON GOLD', 'BOYKING', 'SEA CAPTAIN', 'FAME',
        'COYOTE CASH', 'BIG SHOT', 'CLEOPATRA', 'GIRLS', 'PAYDIRT', 'WILD FOX', 'PROSPERITY', 'WONG CHOY', 'HIGH WAY', 'ZHAO CAI JIN BAO', 'GREAT STARS', 'NIAN NIAN YOU YU ',
        'KIMOCHI', 'CAPTAIN', 'GREEN', 'IRISH LUCK', 'GOLDEN LOTUS', 'SPARTAN', 'FRUIT', 'AFRICAN', 'THE DISCOVERY', 'BONUS BEARS', 'GREAT BLUE'
    ]
}

// EXPORT FUNCTION
export {listKiss};